# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-08-18 10:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0057_auto_20260721_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentVerificationUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.State')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Verification User',
                'verbose_name_plural': 'Payment Verification Users',
            },
        ),
        migrations.AlterUniqueTogether(
            name='paymentverificationuser',
            unique_together=set([('user', 'state')]),
        ),
    ]
