# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-08-31 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0036_domain_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='fosscategory',
            name='download',
            field=models.BooleanField(default=False, help_text='If checked, this foss will be available for CD content download'),
        ),
    ]
